steps:
  - id: 'Install Dependencies'
    name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm ci || npm install'

  - id: 'Build'
    name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'export NODE_OPTIONS="--openssl-legacy-provider" && VUE_APP_WEBSOCKET_URL="${_VUE_APP_WEBSOCKET_URL}" npm run build'

  - id: 'Deploy'
    name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
    args:
      - 'deploy'
      - '--project'
      - '${_FIREBASE_PROJECT}'
      - '--only'
      - 'hosting:${_SITE_ID}'
      - '--debug'

substitutions:
  _FIREBASE_PROJECT: 'firebase-jkbff'
  _SITE_ID: 'aochat-jkbff'
  _VUE_APP_WEBSOCKET_URL: 'wss://aochat-api.jkbff.com/connect'

options:
  logging: CLOUD_LOGGING_ONLY
